logging:
  level:
    ROOT: INFO
spring:
  messages:
    basename: messages
  thymeleaf:
    cache: false
    cacheable: false
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
server:
  port: 8081